name: test

on:
  pull_request:
    branches: ["main", "0.16"]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig build test --summary new
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check .
